# Generated by Django 3.2.20 on 2024-02-24 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='LessonLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_kz', models.CharField(max_length=100, verbose_name='Заголовок на казахском')),
                ('title_ru', models.CharField(max_length=100, verbose_name='Заголовок на русском')),
                ('title_en', models.CharField(max_length=100, verbose_name='Заголовок на английском')),
                ('sub_title_kz', models.CharField(max_length=100, verbose_name='Подзаголовок на казахском')),
                ('sub_title_ru', models.CharField(max_length=100, verbose_name='Подзаголовок на русском')),
                ('sub_title_en', models.CharField(max_length=100, verbose_name='Подзаголовок на английском')),
                ('description_kz', models.TextField(verbose_name='Описание на казахском')),
                ('description_ru', models.TextField(verbose_name='Описание на русском')),
                ('description_en', models.TextField(verbose_name='Описание на английском')),
                ('image', models.ImageField(upload_to='lessons', verbose_name='Изображение')),
                ('audio_kz', models.FileField(upload_to='audio', verbose_name='Аудио на казахском')),
                ('audio_ru', models.FileField(upload_to='audio', verbose_name='Аудио на русском')),
                ('audio_en', models.FileField(upload_to='audio', verbose_name='Аудио на английском')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WordTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(blank=True, max_length=100)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.language')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.word')),
            ],
        ),
        migrations.AddField(
            model_name='word',
            name='languages',
            field=models.ManyToManyField(through='myapp.WordTranslation', to='myapp.Language'),
        ),
        migrations.CreateModel(
            name='LessonTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.language')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.lesson')),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='languages',
            field=models.ManyToManyField(through='myapp.LessonTranslation', to='myapp.Language'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.topic'),
        ),
        migrations.CreateModel(
            name='Alphabet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letters', models.TextField()),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.language')),
            ],
        ),
    ]
